package Clases;
// Generated Oct 11, 2019 10:09:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departments generated by hbm2java
 */
public class Departments  implements java.io.Serializable {


     private Integer depCode;
     private String depName;
     private String city;
     private Set employeeses = new HashSet(0);

    public Departments() {
    }

    public Departments(String depName, String city, Set employeeses) {
       this.depName = depName;
       this.city = city;
       this.employeeses = employeeses;
    }
   
    public Integer getDepCode() {
        return this.depCode;
    }
    
    public void setDepCode(Integer depCode) {
        this.depCode = depCode;
    }
    public String getDepName() {
        return this.depName;
    }
    
    public void setDepName(String depName) {
        this.depName = depName;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Set getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }




}


