package Clases;
// Generated Oct 11, 2019 10:09:20 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private Integer empCode;
     private Departments departments;
     private String empName;
     private String position;
     private BigDecimal salary;

    public Employees() {
    }

    public Employees(Departments departments, String empName, String position, BigDecimal salary) {
       this.departments = departments;
       this.empName = empName;
       this.position = position;
       this.salary = salary;
    }
   
    public Integer getEmpCode() {
        return this.empCode;
    }
    
    public void setEmpCode(Integer empCode) {
        this.empCode = empCode;
    }
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public BigDecimal getSalary() {
        return this.salary;
    }
    
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }




}


